//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// WinLib.rc で使用
//
#define IDSET                           3
#define IDD_PROGBAR                     101
#define IDD_RFDLG                       102
#define IDD_PROGTEXT                    105
#define IDD_CNTDLG                      106
#define IDD_WFDLG                       108
#define IDD_FHDLG                       111
#define IDR_LOG_WND_TOOLBAR             121
#define IDD_INPNUM_DLG                  130
#define IDD_INPFLT_DLG                  131
#define IDD_MLT_INPNUM_DLG              132
#define IDD_MESG_BOX                    133
#define IDC_RF_FNAME                    1000
#define IDC_RF_FROMNUM                  1001
#define IDC_RF_TONUM                    1002
#define IDC_RF_TTL_FNAME                1003
#define IDC_RF_TTL_FROMNUM              1004
#define IDC_RF_TTL_TONUM                1005
#define IDC_CNT_SLIDER_CNTMAX           1006
#define IDC_CNT_CNTMAX                  1007
#define IDC_CNT_SLIDER_CNTMIN           1008
#define IDC_CNT_CNTMIN                  1009
#define IDC_FH_HSIZE                    1020
#define IDC_FH_XSIZE                    1021
#define IDC_FH_YSIZE                    1022
#define IDC_FH_ZSIZE                    1023
#define IDC_FH_DEPTH                    1024
#define IDC_FH_LTLEND                   1025
#define IDC_FH_SAVEP                    1026
#define IDC_FH_BASE                     1027
#define IDC_WF_FNAME                    1030
#define IDC_WF_FROMNUM                  1031
#define IDC_WF_TONUM                    1032
#define IDC_WF_MFL                      1034
#define IDC_WF_FORMATS                  1036
#define IDC_MESG_BOX_TEXT               1038
#define IDC_INM_VALTTL                  1050
#define IDC_INM_VAL                     1051
#define IDC_INM_FLTTTL                  1052
#define IDC_INM_FLT                     1053
#define IDC_PROGBAR_M                   1062
#define IDC_PROGTEXT_MSG                1063
#define IDC_INM_MLT_VALTTL0             1070
#define IDC_INM_MLT_VAL0                1071
#define IDC_INM_MLT_VALTTL1             1072
#define IDC_INM_MLT_VAL1                1073
#define IDC_INM_MLT_VALTTL2             1074
#define IDC_INM_MLT_VAL2                1075
#define IDC_INM_MLT_VALTTL3             1076
#define IDC_INM_MLT_VAL3                1077
#define IDC_INM_MLT_VALTTL4             1078
#define IDC_INM_MLT_VAL4                1079
#define IDC_INM_MLT_VALTTL5             1080
#define IDC_INM_MLT_VAL5                1081
#define IDS_STR_FAIL_GET_DX9DEV         3000
#define IDS_STR_FAIL_CRT_BAKBUF         3001
#define IDS_STR_FAIL_TRNS_BAKBUF        3002
#define IDS_STR_FAIL_CRT_SURFACE        3003
#define IDS_STR_FAIL_TRNS_SURFACE       3004
#define IDS_STR_FAIL_CLR_WND            3005
#define IDS_STR_FAIL_RESTR_DX9DEV       3007
#define IDS_STR_FAIL_INIT_OPENNI        3008
#define IDS_STR_FAIL_REINIT_OBJ         3010
#define IDS_STR_FAIL_REGET_BAKBUF       3013
#define IDS_STR_FAIL_REGET_SURFACE      3014
#define IDS_STR_FAIL_RETRNS_SURFACE     3015
#define IDS_STR_FAIL_GET_INPDEV         3020
#define IDS_STR_FAIL_GET_MUSDEV         3021
#define IDS_STR_FAIL_GET_KEYDEV         3022
#define IDS_STR_UNSPT_VWMODE            3025
#define IDS_STR_INVLD_VWMODE            3026
#define IDS_STR_UNKWN_VWMODE            3027
#define IDS_STR_NULLPT_FRM              3030
#define IDS_STR_CANCEL_OPRTN            3031
#define IDS_STR_ERR_OPEN_FILE           3032
#define IDS_STR_ERR_UNDISP              3033
#define IDS_STR_ERR_PREDISP             3034
#define IDS_STR_ERR_MEMORY              3036
#define IDS_STR_FAIL_COPY_FLDATA        3037
#define IDS_STR_ERR_UNKWN               3038
#define IDS_STR_CANCEL_TRNS_DATA        3039
#define IDS_STR_CANCEL_OPNFILE          3040
#define IDS_STR_CANCEL_VERTEX_BUF_SET1  3041
#define IDS_STR_CANCEL_VERTEX_BUF_SET2  3042
#define IDS_STR_INFO_VERTEX_ZERO        3043
#define IDS_STR_ERR_VERTEX_NUM          3044
#define IDS_STR_FAIL_GET_VERTEX_BUF     3045
#define IDS_STR_ERR_READ_FILE           3046
#define IDS_STR_ERR_WRITE_FILE          3047
#define IDS_STR_UNSPT_DATA              3100
#define IDS_STR_IMP_PROCESS             3101
#define IDS_STR_DLTD_DATA               3102
#define IDS_STR_OK                      3110
#define IDS_STR_ERROR                   3111
#define IDS_STR_CNFRM                   3112
#define IDS_STR_UNUSED                  3113
#define IDS_STR_CANCEL                  3114
#define IDS_STR_INFO                    3115
#define IDS_STR_UNKWN                   3116
#define IDS_STR_ATTNSN                  3117
#define IDS_STR_WARN                    3118
#define IDS_STR_WRTNG_FILE              3120
#define IDS_STR_RDNG_FILE               3121
#define IDS_STR_CANCELING               3122
#define IDS_STR_CNFRM_CNTNUE            3123
#define IDS_STR_TRNS_DISPDATA           3124
#define IDS_STR_IMG_NUM                 3125
#define IDS_STR_NEXT_QUSTN              3126
#define IDS_STR_PROC_VERTEX_BUF         3127
#define IDS_STR_OPEN_FILE               3128
#define IDS_STR_DEL_DATA                3129
#define IDS_STR_CANCELD_PROC            3130
#define IDS_STR_RSLT_PROC               3131
#define IDS_STR_SPECIFY_SAVE_FILE       3133
#define IDS_STR_SPECIFY_LOAD_FILE       3134
#define IDS_STR_FONT_SIZE               3150
#define IDS_STR_FONT_MINCHO             3151
#define IDS_STR_FONT_GOTHIC             3152
#define IDS_STR_ASK_LOG_CLEAR           3201
#define IDS_STR_ASK_OVERWRITE           3210
#define IDS_STR_LOCALE                  4700
#define ID_LOG_SAVE                     9001
#define ID_LOG_CLEAR                    9002
#define ID_LOG_COPY                     9003
#define ID_JBXWL_DUMMY                  35000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
